name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.13"]
        #python-version: ["3.8", "3.9", "3.10", "3.11"] # for binary builds we only need one version
    steps:
    - uses: actions/checkout@v4
    - name: NetExec set up python on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Native Binary
      run: |
        pip install pyinstaller pillow
        pip install .
        pyinstaller netexec.spec
    - name: Upload Windows Binary
      if: runner.os == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: nxc-windows.exe
        path: dist/nxc.exe
    - name: Upload Nix/OSx Binary
      if: runner.os != 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: nxc-${{ matrix.os }}
        path: dist/nxc
